package pl.lodz.p.it.ssbd2020.ssbd05.mok;// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.interactions.Actions;

import java.util.UUID;

public class AddAccountTestUI {
  private WebDriver driver;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    WebDriverManager.getInstance(ChromeDriver.class).setup();
    ChromeOptions options = new ChromeOptions();
    options.setHeadless(true);
    options.addArguments("--lang=en");
    options.setAcceptInsecureCerts(true);
    driver = new ChromeDriver(options);
    js = (JavascriptExecutor) driver;
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addAccount() throws InterruptedException {
    UUID random = UUID.randomUUID();
    String randomString = random.toString().replace("-","");
    randomString = randomString.substring(0,10);
    driver.get("https://localhost:8181/ssbd05/login/login.xhtml");
 //   driver.manage().window().setSize(new Dimension(1936, 1056));
    driver.findElement(By.id("loginButton")).click();
    driver.findElement(By.id("login:loginPnl_content")).click();
    driver.findElement(By.id("login:username")).click();
    driver.findElement(By.id("login:username")).sendKeys("admin");
    driver.findElement(By.id("login:password")).click();
    driver.findElement(By.id("login:password")).sendKeys("admin123");
    driver.findElement(By.cssSelector(".ui-button-text:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".ui-button-text:nth-child(2)")).click();
    Thread.sleep(1000);
    driver.findElement(By.xpath("//span[contains(.,\'Change role\')]")).click();
    Thread.sleep(1000);
    driver.findElement(By.linkText("Admin")).click();
    driver.findElement(By.cssSelector(".pi-bars")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".pi-bars"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector("#addAccountButton > .ui-button-text")).click();
    Thread.sleep(1000);
    driver.findElement(By.id("register:login")).click();
    driver.findElement(By.id("register:login")).sendKeys("AddAccountTest" + randomString);
    driver.findElement(By.id("register:password")).click();
    driver.findElement(By.id("register:password")).sendKeys("AddAccountTest!@1");
    driver.findElement(By.id("register:confirmPassword")).click();
    driver.findElement(By.id("register:confirmPassword")).sendKeys("AddAccountTest!@1");
    driver.findElement(By.id("register:firstName")).click();
    driver.findElement(By.id("register:firstName")).sendKeys("Addtest");
    driver.findElement(By.id("register:lastName")).click();
    driver.findElement(By.id("register:lastName")).sendKeys("Addtest");
    driver.findElement(By.id("register:emailAddress")).click();
    driver.findElement(By.id("register:emailAddress")).sendKeys(randomString +"@eoopy.com");
    driver.findElement(By.xpath("//table[@id=\'register:accessLevels\']/tbody/tr/td/div/div[2]/span")).click();
    driver.findElement(By.xpath("//table[@id=\'register:accessLevels\']/tbody/tr/td[2]/div/div[2]/span")).click();
    driver.findElement(By.xpath("//div[@id=\'register:active\']/div[2]/span")).click();
    driver.findElement(By.cssSelector("#register\\3Asubmit > .ui-button-text")).click();
    driver.findElement(By.xpath("//div[3]/button/span[2]")).click();
    Thread.sleep(1000);
    Assert.assertEquals(driver.findElement(By.cssSelector(".ui-growl-title")).getText(),"Account created!");
  }
}
