package pl.lodz.p.it.ssbd2020.ssbd05.mok;// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;

import java.util.UUID;

public class RegisterTestUI {
    private WebDriver driver;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        WebDriverManager.getInstance(ChromeDriver.class).setup();
        ChromeOptions options = new ChromeOptions();
        options.setHeadless(true);
        options.addArguments("--lang=en");
        options.setAcceptInsecureCerts(true);
        driver = new ChromeDriver(options);
        js = (JavascriptExecutor) driver;
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void register() throws InterruptedException {
        UUID random = UUID.randomUUID();
        String randomString = random.toString().replace("-","");
        randomString = randomString.substring(0,10);
        driver.get("https://localhost:8181/ssbd05/index.xhtml");
        driver.manage().window().setSize(new Dimension(1936, 1056));
        driver.findElement(By.id("registerButton")).click();
        Thread.sleep(200);
        driver.findElement(By.id("register:login")).click();
        driver.findElement(By.id("register:login")).sendKeys("RegisterTest" +randomString);
        driver.findElement(By.id("register:password")).click();
        driver.findElement(By.id("register:password")).sendKeys("Password123@");
        driver.findElement(By.id("register:confirmPassword")).click();
        driver.findElement(By.id("register:confirmPassword")).sendKeys("Password123@");
        driver.findElement(By.id("register:firstName")).click();
        driver.findElement(By.id("register:firstName")).click();
        driver.findElement(By.id("register:firstName")).sendKeys("Test");
        driver.findElement(By.id("register:registrationPanel_content")).click();
        driver.findElement(By.id("register:lastName")).click();
        driver.findElement(By.id("register:lastName")).sendKeys("Test");
        driver.findElement(By.id("register:registrationPanel_content")).click();
        driver.findElement(By.id("register:emailAddress")).click();
        driver.findElement(By.id("register:emailAddress")).sendKeys(randomString + "s@eoopy.com");
        driver.findElement(By.cssSelector("#register\\3AregistrationPanel_content > div:nth-child(2)")).click();
        driver.switchTo().frame(0);
        driver.findElement(By.cssSelector(".recaptcha-checkbox-border")).click();
        Thread.sleep(2000);
        driver.switchTo().defaultContent();
        driver.findElement(By.cssSelector("#register\\3Asubmit > .ui-button-text")).click();
        Thread.sleep(1000);
        Assert.assertEquals("Account created!", driver.findElement(By.cssSelector(".ui-growl-title")).getText());
    }
}
